### ISSUE TITLE
Unable to find device.

### ISSUE THREAD

**Issue by jedahan** [tolga9009/elgato-gchd#1]
I tried changing the PID to 0x0051 which is what lsusb -v shows for my elgato.

I compiled with `gcc -std=c99 -Wall -Wextra elgato-gchd.c -lusb-1.0 -o elgato-gchd`

Not sure what next steps to take. On kernel 3.17.0 ...

**Comment by tolga9009** [comment]
Small update: I'm done with the cleanups so far. It makes reading the code and finding patterns much easier! I've been working on the lines 11046+ in mac_setup_device. There are highly repetitive parts. It looks like the driver is polling the device until it's ready to stream data. There are about 10 - 20 individual packets, which get repeated over and over in a specific pattern. I wasn't able to replicate this pattern, as there are still some individual packets, which break the pattern.

Based on jedahan's work, I'm now working on a small utility to help me analyze the logs.

I'll keep you updated!
