### ISSUE TITLE
1080p not working

### ISSUE THREAD

**Issue by tolga9009** [tolga9009/elgato-gchd#10]
Currently, this driver only handles non-encrypted (HDCP-free) 720p60 input and outputs 720p60 to a file. 1080p (input / output) isn't working properly. I'm getting a weird output from a 1080p60 source. Only parts of the 1080p60 are visible and the produced output video is 720p.

My holiday season begins on 17 December and I'm extremely motivated working on this driver again! The 1080p support might be a cool christmas present. Let's see if I can do it ;)! I'll keep you updated about it.

**Comment by tolga9009** [comment]
1080p support has been added in the new 1080p branch. Fixed by f2a1badb4abb53c7f7e97e959221814407f0d3ab.

**Comment by EtiennePerot** [comment]
Very nice. Does this support 60fps as well? If not, would it be hard to add? I'm considering buying the 60fps model so I'd like to know in advance.

**Comment by tolga9009** [comment]
The Elgato Game Capture HD only supports 1080p30, since it's hardware limited and has nothing to do with software implementation. The Elgato Game Capture HD60 supports 1080p60, but is not supported by this driver, as I do not own the HD60 to work on this. The HD60 seems to have a different hardware, so it is impossible for me to reverse engineer it, without getting my hands on one.

But also please note, that the latest revision of Elgato Game Capture HD cards (PID 0x005d, manufactured in late 2014) also do not work with this driver, due to some small modifications made to the hardware. So, if you're willing to record 1080p60, you'll need to grab the HD60 and use Windows at the moment.
