### ISSUE TITLE
PID 0x005d not working

### ISSUE THREAD

**Issue by tolga9009** [tolga9009/elgato-gchd#12]
New versions of the Elgato GCHD don't seem to work with this driver, as found out by @rosimildo and @Romans-I-XVI. They seem to have a slightly modified init sequence and probably are using a different firmware file (and maybe even slightly modified hardware). I need USB capture logs to work on this, as I don't have my hands on the latest revision. @rosimildo, can you help me with this one?

Cheers,
Tolga

**Comment by Romans-I-XVI** [comment]
Sent you a log, good luck :+1:

**Comment by rosimildo** [comment]
I am on vacation and will be back home next week!
I still have a capture from last year, I believe!

Let me see what I can do when I return home!

R

**Comment by tolga9009** [comment]
@Romans-I-XVI: Thank you! Unfortunately, it looks like an unsuccessful attempt - some fields are missing. I'll post you new instructions for logging USB traffic using Wireshark tomorrow. It's more mature than Microsoft Message Analyzer.

@rosimildo: Thanks for looking into this! I would need you to capture new USB logs though, since the drivers' current state is based on the latest 3.00.111 (Windows) release. I will post detailed instructions, so the logs are comparable with mine. But enjoy your vacation first ;)!

Cheers,
Tolga

**Comment by Lagg** [comment]
@tolga9009 I can provide capture logs of this as @EtiennePerot recently got me the Game Capture HD. But  you have to help me figure out this strange new design in the latest version of wireshark. More or less got it figured out myself but it's still pretty weird looking.

**Comment by tolga9009** [comment]
Thank you @Lagg! I've also received another capture log by E-Mail. The new revision Elgato GCHDs seem to have a Fujitsu MB86M01 sitting in it's heart, instead of its predecessor, the Fujitsu MB86H57. The amount of RAM seems to be doubled to 1Gbit and the recording delay seems to be optimized. Aside from that, the changes are just for cutting costs.

The boot process got a bit simplified, by moving some parts directly to the device itself. It's also using another firmware, `mb86m01_assp_nsec_idle.bin` and `mb86m01_assp_nsec_enc.bin`. I wasn't able to fully dive into the capture logs, but I think this is definitely doable, without having a new revision Elgato sitting next to me.

As soon as I find something new, I will update you guys on this matter.

**Comment by HitsuMaruku** [comment]
@tolga9009 It appears I have this revision. I tried altering the code to use the new firmware you specified, but it seems the same as using the old firmware (I did not expect it to work, but thought it may do something different). If you can supply instructions, I would be happy to help with supplying log files (if you still need them).

**Comment by tolga9009** [comment]
@HitsuMaruku thanks for your test, I already assumed, that it wouldn't work like that. I already have 2 other captures, which will probably do the job. Also, I have a script file on my hand, which describes the boot procedure on the new PID 0x005d devices. It's slightly different than the previous revision Elgato GCHDs, but it isn't something completely new. I think it should be doable with the captures I currently have on my hands.

Please note, I'm not actively working on this driver at the moment - I'm planning the next session in February / March.

**Comment by boazzzz** [comment]
@tolga9009 appriciate the hard work, would be happy to hear news on it, any chances it will be ready soon?

**Comment by tolga9009** [comment]
@boazzzz I don't know yet. It's more work, than I originally thought, but it still isn't impossible. Currently, I'm very busy with real life, so just don't hold your breath. I will keep you updated on this, but if you need the Elgato anytime soon, I recommend using Windows.

**Comment by boazzzz** [comment]
Thanks mate :)

**Comment by oleerik** [comment]
Hello @tolga9009 :)

I also have one of those, and it indeed does not work. 
Is there anything I can do or provide to help out?

Thank you for your work thus far!

**Comment by CodePanter** [comment]
I am pretty sure I have this version of the Elgato as well, because I get the "This revision of the Elgato Game Capture HD is currently not supported." error message. If there is any way I can help fix this, just let me know!

**Comment by Leseratte10** [comment]
I plan to buy an Elgato Game Capture HD to use it under Linux. Is there any way (different package, anything) I could find out whether a copy offered in an (online) shop is the old version (supported by this driver) and which is the new one?

Or, is there any estimated release date for the "new" driver?

**Comment by tolga9009** [comment]
Hi @Leseratte10,

as far as I know, there is no way to find out which revision of the GCHD you will get. I think the "safest" way would be looking on ebay and asking sellers, if they could read out the VID PID (can be done in Windows's native Device Manager, or System Information or 3rd party tools).

Unfortunately, I don't have an ETA. I have received some captures, but since it's in another format, it's not easy to compare with capture collection.

@All: if there is anyone located in Germany / Niedersachsen / NRW with a Game Capture HD 0x005d, please let me know.

**Comment by petl** [comment]
@tolga9009: I do have the 0x005d. I'm running 14.04 and it shows me the "This revision of the Elgato Game Capture HD is currently not supported." error. I'm from Vienna, so not exactly Germany but close.

**Comment by shanedc** [comment]
I'm just curious, but I've scoured Google and haven't found anything. And since the thread is about 3 months old I feel like it's okay to necro this. Is there any update to this 0x005d thing?

**Comment by tolga9009** [comment]
I have no possibility to work on the new revision Elgato GCHDs at the moment. Don't expect any updates on this, until I can get my hands on a unit.

**Comment by Criptos** [comment]
tolga,  you need the device or  just having acces to a computer with it? 
I can led you my laptop, I'm at mexico... sending it would expensive, I can support with some money for you to purchase it...  

And yes.. I have one el gato 5d...

**Comment by tolga9009** [comment]
@Criptos my current tools require me to have physical access to the device. This is due to my USB capture hardware OpenVizsla (http://openvizsla.org/).

I'm currently working on the HD60, for which I'm porting my tools over to usbmon. Once done, having access to a PC + Elgato GCHD 0x005d over VPN / VNC will be enough.

The whole development stagnated a bit at the moment though. That's why I can't give any ETA, I'm sorry.

**Comment by CodePanter** [comment]
@seveirein I haven't been able to test it yet, but I assume https://github.com/tolga9009/elgato-gchd/commit/4c290327d9d43e2383a9b54f24a62bbcfaba0317 fixes this issue?

**Comment by tolga9009** [comment]
@seveirein worked on a few bunch of things, not only limited to 0x005d device (I'd like to call it GCHD2) support. Currently, development will be done in `dev` branch and later  merged to `master` branch, once everything works as intended.

The driver is getting a huge overhaul, thanks to the work of @seveirein. Currently though, `dev` only works for 0x005d devices. So, if you have the GCHD1, you cannot use it. But I'm sure, it won't take long, until we got it working aswell. And HD60 of course.

Feel free to clone and test `dev` branch. Please keep in mind it's under heavy development, so bug reporting should be limited for now.

Cheers,
Tolga

**Comment by CodePanter** [comment]
I have the GCHD2, and went ahead and cloned the dev branch. It detects the device and it's correct PID, and it starts up fine. However it crashes whenever I open 'gchd.ts' with VLC, or when I turn the format to 'disk'. 
My command (ran as root):
`sudo ./gchd -o /home/CodePanter/elgato-output/gchd.ts -r 720 -f disk`
The error:
`Saving to disk: /home/CodePanter/elgato-output/gchd.ts
Initializing device.
Firmware Version is V1300230
terminate called after throwing an instance of 'usb_error'
  what():  libusb_control_transfer did not return all bytes.`

**Comment by tolga9009** [comment]
This is currently beeing worked on and caused by an issue, which prevents the device to correctly reset and resume.

A temporary fix is to replug the Elgato and try it again.

**Comment by CodePanter** [comment]
Replugging the device did not work, I did this several times. It crashed the same way every time. I also tried both specifying and not specifying the output location and resolution, I wasn't sure if any of these settings had to do with it, but they didn't change anything either.

**Comment by CodePanter** [comment]
I cloned the newest version of the repository, made sure all necessary files were in place and built it. I started the usb monitor, plugged the GCHD2 in, and started the software, as root. I then started VLC, and opened the gchd.ts file. I waited for a while, then pressed CTRL + C, to stop the software. I then quit VLC, and unplugged the device. All throughout this, I didn't see any video. 
Software output:

> FIFO: /tmp/gchd.ts has been created.
Waiting for user to open it.
Initializing device.
Firmware Version is V1300230
No signal found. Defaulting to HDMI
^C
Stop signal received.

I sent you an e-mail with the usb capture.

**Comment by tolga9009** [comment]
Thanks for the E-Mail, just responded. As for your procedure: it's correct. Question about your source though: which HDMI source are you using? To me, it looks like your Elgato doesn't find a HDMI source. This could be a HDCP-protected source (like PS3) or PS4 with HDCP enabled. Xbox360 doesn't have HDCP and I'm unsure about Xbox One.

In case you have a PS4, you can disable HDCP via menu. For PS3, you'll need an external device to bypass HDCP (illegal in some countries) or a CFW, which supports bypassing HDCP via system menu.

For testing purposes, I'd recommend you to use a non-HDCP HDMI source, like your everday computer. Set it to 1080p and try again.

I will give you more details, once I receive the full USB capture.

Cheers,
Tolga

**Comment by tolga9009** [comment]
We need more testers for `dev` branch. Please check issue #27. Thanks!

**Comment by tolga9009** [comment]
GCHD2 (0x005d) support has been added in commit 03959cc4cf63659ff639c5c8c99965f99938756a by Scott Dossey. Thanks for the patches, Scott!

If you have any issues, please open a new ticket.
