### ISSUE TITLE
Cleanup incomplete

### ISSUE THREAD

**Issue by Gotos** [tolga9009/elgato-gchd#3]
Hi!
I just tested your Software, it's works like a charm! The only thing I found not to work is the clean up - once I stopped capturing I have to physically dis- and reconnect the GCHD to start a new capture. If I try to start a new capture without reconnecting the GCHD the software just hangs and needs to be killed - ctrl + c won't do the trick.

**Comment by tolga9009** [comment]
Hi there,

unfortunately, I have no time to work on this project at the moment and have never really worked on cleanups. I was glad enough, when the video capture worked on Linux. So, I never really looked at how the Windows driver is resetting the device. My USB hardware analyzer has very limited amount of RAM, which is not enough for long captures (talking about 10+ seconds on USB High-Speed).

Probably, I'm gonna continue working on these drivers in about 3 - 4 weeks.

Cheers,
Tolga

**Comment by tolga9009** [comment]
b5e46776bbe5a44599951e162375497e4837454b fixed this. When you terminate the driver using CTRL + C, wait a couple of seconds for the driver to gracefully shutdown / reset your device. After the program has successfully terminated, you will be able to re-run it, without needing to replug your device.

Closing this issue now. Thanks for reporting!
