### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by lyleunderwood** [tolga9009/elgato-gchd#30]
I feel like I have this close to working, but so far it has just output zero bytes. I've tried a bunch of different input / output options, all of the output options just never get any output. In this example, my output file is created but always ends up with zero bytes:

```bash 
$ sudo strace ./gchd -i hdmi -or 1080 -output-format disk /home/lyle/junk 1>/tmp/el 2>/tmp/el
```

Here's the strace log:

https://gist.github.com/lyleunderwood/3d07962fcf41dbded41febfe188bbab2

I'll call attention to the tens of thousands of lines at the end where it appears to be stuck in a loop:

```
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309f0) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309f0) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0xd6c3c0)  = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309f0) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309f0) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0xd6c3c0)  = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309e0) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309e0) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0xd6c3c0)  = 0
poll([{fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLOUT}])
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309e0) = 0
ioctl(9, USBDEVFS_REAPURBNDELAY, 0x7fffb90309e0) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(9, USBDEVFS_SUBMITURB, 0xd6c3c0)  = 0
```

etc.

**Comment by tolga9009** [comment]
Hi and thank you for the bug report!

A few people experienced issues with non-working output. I would like to point out, that you currently have to replug your Elgato between attempts, as our code has issues with properly resetting the device at the moment.

If this doesn't fix your issues, you might try out the latest patch at https://github.com/seveirein/elgato-gchd by Scott Dossey. I'm going to apply that patch onto this repo's `master` branch, once I've personally successfully tested it.

I would like to ask, which input source you're trying to capture. E.g. HDCP-protected sources (like PS3) can't be captured, without bypassing HDCP first, using an external device. Also, some audio formats (Dolby Surround) might make your capture fail aswell.

Please let us know, if anything above helped you.

Cheers,
Tolga

**Comment by lyleunderwood** [comment]
That patch fixes it! Now I just have colorspace issues, but I've seen them addressed elsewhere so I should be able to solve them myself from here. Thanks a bunch. Here's some more description of the issue I was seeing for posterity's sake:

I was trying to capture an ubuntu pc over HDMI running a standard pulseaudio setup as far as I know. 

I was definitely replugging the Elgato. Here's a rundown of what was actually happening:

1. start gchd
2. start reading data (or start writing to disk)
3. passthru turns off, meaning black screen on the input device
4. the loop in libusb described above is now occurring
5. unplug Elgato
6. gchd throws some libusb error and exits
7. replug Elgato
8. passthru starts working again

With the patch passthru starts working again and data is successfully being written.

One thing I had a hard time finding was what cli output was supposed to look like upon success, so here's mine now that it's working:

```
sudo ./gchd -output-format disk ~/junk2.ts
[sudo] password for lyle: 
Saving to disk: /home/lyle/junk2.ts
Initializing device.
Hardware revision is V1100090
HDMI input found?

Configured Mode:
HDMI 1920x1080@60hz (progressive scan). YUV color space. Aspect ratio is: 16:9.

Streamer has been started.
```

Before I had never gotten to the "Configured Mode:" line.
