### ISSUE TITLE
Any plan to support the Elgato CAM Link?

### ISSUE THREAD

**Issue by farleylai** [tolga9009/elgato-gchd#42]
Or is it already supported?
Just a plain capture function would suffice.
No hardware encoder in this device.

**Comment by tolga9009** [comment]
Hi!

Sorry for the late answer. To my understanding, the Elgato Cam Link device is a UVC-compliant device, which means most operating systems will deal with it like a webcam. It should work out-of-the-box on any recent Linux distribution and even OS X - without additional drivers. Therefore, no support needed nor planned.

I've found a YouTube video, where someone is using the device successfully under Linux: https://www.youtube.com/watch?v=fYilWEonHHA.

I'm closing the issue, feel free to reopen, if this doesn't fully answer your question.

Cheers,
Tolga

**Comment by farleylai** [comment]
Sounds great. Gonna give it a shot soon.
