### ISSUE TITLE
Won't compile with g++

### ISSUE THREAD

**Issue by Gotos** [tolga9009/elgato-gchd#6]
As I don't have clang installed, I tried changing the Makefile to use g++, which worked for the last version I tried. Now I get this error:
commands.c:18:46: Fehler: ungültige Umwandlung von »void*« in »unsigned char*« [-fpermissive]
  recv = calloc(wLength, sizeof(unsigned char));

(This translates to "Error: invalid conversion from »void*« to »unsigned char*« [-fpermissive]
  recv = calloc(wLength, sizeof(unsigned char));")

**Comment by tolga9009** [comment]
Hi Gotos,

the latest code base is written in C, not C++ anymore. Please use gcc instead of g++. Please report back.

Cheers,
Tolga

**Comment by Gotos** [comment]
That did the trick, thanks!
