### ISSUE TITLE
No output from Elgato HDMI port while the driver is active

### ISSUE THREAD

**Issue by StianOby** [tolga9009/elgato-gchd#7]
When the driver is running the HDMI out port on my Elgato Game Capture HD is not sending a signal. (At least this is what my monitor is telling me - I only have a single monitor with 2x HDMI that I switch between using the panel on the side.)

Even after I close OBS and shut down the elgato-gchd driver cleanly (with CTRL+C), I still can't get a signal from the HDMI-Out on the GameCapture HD. I have to reset the device by unplugging and replugging the USB cable.

**Comment by StianOby** [comment]
**Did some more research, and here are my findings:**
(Xbox is set to 720p for all tests)
* Before starting the driver: can switch to the Xbox input on my LCD screen.
* Driver started using the command sudo ./elgato-gchd. I can still switch to the Xbox input on my LCD monitor.
* Open /tmp/elgato_gchd.ts in VLC and keep it running. Xbox output visible in VLC, as expected. It is _now impossible_ to switch to the Xbox input on my LCD monitor. Same reaction from the screen as if there was no signal.
* Close VLC. Still impossible to switch to the Xbox input on my LCD monitor.
* Close the driver (Ctrl+C in the terminal). Clean shutdown of the driver, removing /tmp/elgato_gchd.ts automatically as expected. But it is still impossible to switch to the Xbox input on my LCD monitor.

I hope this can help you track down the problem!

**Comment by ajclarke** [comment]
I also got this behaviour when trying this driver a few weeks ago, but I forgot to actually report it until now. What I interpreted it as was that the windows driver and the firmware that it uploads on to the elgato supports the pass through feature - this linux driver doesn't. So as soon as you use this to record you are unable to use the passthrough feature again until you connect the elgato to a windows machine running the elgato software, which restores the old firmware with the feature to the device. At least that was my experience.

I also ran in to a different problem which I will create an issue for too.

**Comment by StianOby** [comment]
I did not need to connect it to a windows machine to get input, though. Just needed to unplug/replug on my Linux machine.

**Comment by tolga9009** [comment]
I have a theory, why it isn't working. It is probably due to my specific reverse engineering setup. I have used a PS3 HDMI -> HDCP Stripper -> HDMI Splitter -> HDMI In (Elgato) -> OpenVizsla USB Analyzer -> PC. I didn't use the Elgato's HDMI Out Port during my capturing sessions. Most probably, the software is recognizing, whether HDMI Out is connected or not. In my special case, HDMI Out was not connected, so the software simply might have skipped the initialization part of the HDMI Out port. I think I need to recapture the USB traffic with HDMI Out connected.

I think replugging should be enough to restore the original device status. The binary files loaded onto the device are non-permanent. Think of it like micro-code loaded onto x86 CPUs each boot or firmwares loaded onto FPGAs. There is also a device firmware, which can be updated and permanently written onto the device, but I'm not touching it.

**Comment by StianOby** [comment]
That sounds like a promising theory. Hope you will be able to check it out soon. Thanks for the efforts so far, too!

**Comment by StianOby** [comment]
Have you been able to capture USB traffic with HDMI out connected yet?

(I guess you might be on vacation, if so I am sorry for pinging you)

**Comment by tolga9009** [comment]
I was enjoying holidays and gaming alot, sorry for the silence. About elgato-gchd: after porting my code from C++ back to C, I've been facing some issues, which I couldn't fix. At some point in the code, there must be an error, which leads to undefined behavior. The output file / FIFO pipe sometimes is unreadable, sometimes it's working just fine. This makes working on the code extremely difficult. And it makes me crazy. Need to fix it first.

Also, I got demotivated after reverse engineering the sparam() function. There are inconsistencies between the script and the actual capture log, so wasn't able to successfully find the algorithm and wasted countless hours. I've dropped my work after this fail (but no worries, I'm still racking my brain about it, even if I'm not actively writing code).

Please don't hold your breath. Sometimes I'm making huge jumps, sometimes I'm falling back 2 steps. I will keep you guys up-to-date, as soon as there is any progress.

**Comment by tolga9009** [comment]
e84ba25f8341876c2337a8ddfa43e962137aa340 fixed this issue. Please reopen this issue, if the problem persists.
