### ISSUE TITLE
Colour slightly off when recording from PC

### ISSUE THREAD

**Issue by ajclarke** [tolga9009/elgato-gchd#8]
So using the driver to capture from my XBox seems to work flawlessly, but when trying to capture from my (other) PC, the colours are slightly off. Any idea what might be the cause of this? I've attached a couple of screenshots below to show what I mean:

On XBox 360:
![xbox](https://cloud.githubusercontent.com/assets/4850886/8678426/708d7b60-2a4c-11e5-8d79-d0b64b88768e.png)

On PC:
![pc](https://cloud.githubusercontent.com/assets/4850886/8678425/70616458-2a4c-11e5-83aa-3e647f78f34c.png)

**Comment by StianOby** [comment]
Maybe it has something to do with the RGB Full/Limited distinction: http://referencehometheater.com/2014/commentary/rgb-full-vs-limited/

**Comment by tolga9009** [comment]
I've just come across the same issue. Probably due to setting up the Elgato for Xbox360 and using PC as a source. @StianOby yes, might also be related to RGB color space.

**Comment by tolga9009** [comment]
Okay, I've finally identified the issue for this. The driver currently seems to support the YCbCr444 colorspace. If you're using an RGB source, the colors are going to be off. Luckily, atleast NVIDIA graphics driver on Linux (don't know about Windows or AMD) supports switching colorspace.

I will be fixing this next - gonna take a few days to weeks though.

**Comment by bloodywing** [comment]
I have a similar issue and tried to swap colorspaces without success, because this looks like it is independent from x11.

I get correct colors when I switch to 720p / HDMI / PC output
But on 1080p I get the greenish tone like in the screenshots above. I think I could correct it when encoding the TS file but drawing on a wacom with a tone like this is awful :)

So for me this affects both the pass-thru and the stream file.

**Comment by tolga9009** [comment]
Thanks for reporting. I've already captured logs to fix this issue. However, I will need to make lots of changes to the code before. It's a bit weird, that 720p works fine and 1080p has these issues though. I'm trying to get it working over the weekend, I'll keep you updated.

Cheers,
Tolga

**Comment by Broders** [comment]
Bug also appears on my PS4 and WiiU with 1080p on.
![ccyk0lnxeaatrfp](https://cloud.githubusercontent.com/assets/7099092/13547498/0908b00c-e2d6-11e5-919f-563d9d6a425b.jpg)

**Comment by tolga9009** [comment]
I was finally able to fix the green tint issue. The purple tint issue still needs to be fixed seperately though. Once I have polished it, I will update the README and merge this fix into master.

**Comment by tolga9009** [comment]
Fixed green tint in 2e330e88d2c82398266227ed3cc3b139479dc33d and purple tint in 2df000d2b56ad9a5041ac8788b980a5a882f65e7. You can use commandline option `-c rgb` for RGB sources (former green tint) or `-c yuv` (default) for YUV sources (former purple tint).

Closing this issue. Feel free to reopen, if you still encounter it.
